language: android
script: ./gradlew build test
deploy:
  provider: releases
  api_key: $GITHUB_DEPLOY_OAUTH_TOKEN
  file: app/build/outputs/apk/*.apk
  skip_cleanup: true
  on:
    tags: true
android:
  components:
  - platform-tools
  - build-tools-26.0.1
  - android-26
before_script:
- $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
before_install:
- openssl aes-256-cbc -K $encrypted_fe852ca4e71c_key -iv $encrypted_fe852ca4e71c_iv
  -in OA.jks.enc -out ~\/Desktop/TravisCI/files/OA.jks -d
- openssl aes-256-cbc -K $encrypted_fe852ca4e71c_key -iv $encrypted_fe852ca4e71c_iv
  -in id_rsa.enc -out id_rsa -d
