language: android

jdk: oraclejdk8

notifications:
  email: false

sudo: false

android:
  components:
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - extra-android-support

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assembleRelease

before_deploy:
  - mv app/build/outputs/apk/app-release.apk

deploy:
  provider: releases
  api_key:
    secure:
  file: app/build/outputs/apk/buff.apk
  skip_cleanup: true
  on:
    tags: true
