language: android
script: "./gradlew build test"
deploy:
  provider: releases
  api_key: fba66ee0f277a5e21fdd59586a0ee1820a6d0398
  file: app/build/outputs/apk/*.apk
  skip_cleanup: true
  on:
    tags: true
android:
  components:
    - platform-tools
    - build-tools-26.0.1
    - android-26
before_script:
#  - chmod +x gradlew
  - $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"