language: android
sudo: false
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
  - extra-android-support
script:
-  ./gradlew assembleRelease --stacktrace
before_script:
- $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- openssl aes-256-cbc -K $encrypted_fe852ca4e71c_key -iv $encrypted_fe852ca4e71c_iv
  -in OA.jks.enc -out files/OA.jks -d
deploy:
  provider: releases
  api_key:
    secure: QA9qgTes10as4eKTQEQNivnzGcWCF22TpvPF4xq2IYXpbjpyh2Nl6KkIAikli+vsQQYvLzR69qandFEt2MoNo1k6rdblzkKzmLqf50CvayKcgqOueqmmVAFXob7NaAwffbMlxuJKb6+4916A4Effy7WJ0TBkAxIH8WfY+YLqKx+iIkxwvzx0a9YfScKYw9jBy+Cb0GgH64km9ZlNjK9DmsQGuISLOFX6pYUWksvH5iQfxG8j0TUx1ST4xp92drENLmftCtcDIzRPgl+JCiS+AsXT3HJeJ81xh135djAw6Q0FqJkFZbzzLPFGuafpUXpdOLLxP1owfH223NPIxVhP3XCOXqp4+UNwmDB4em8wGD3pjdNhAv+T7XMRdSfbXNRlszWOxh9FZZa9ePsDtguSkaELCzPh7N7O6q75sCfBo4i0Xdc62OdozWSo3cidNVcQsFOPHOCr1JUihOcOFu9zuH/9Vlm/fZJytcXg1+MwqujuqiXOIU3CsBo+lptLOGtEvDB/E1Jo7dPoKJpFuIhBy4No+NH2+ssCKJR06et0yV3O1PcmnW8NvlRJmmefxiAle/LJbrWfUkmX81jTANSLw8v0IKX7sirkuHbtyDZeyltxQtpZ1oTRMRJUQugnmKAKMyFLbEz7LHBFZ21f2ncS7tu7X/v+G6Tn9Wi2Ld+i1as=
  file: /app/build/outputs/apk/app-release.apk
  on:
    repo: chouchouyu/TravisCI
